config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:'pages#home'

  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'

  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end

  resources :guides do
    resources :reviews, only: [:index, :new, :create]
    resources :stops, only: [:index, :new, :create] do
      resources :itineraries, only: [:new, :create]
    end
    resources :wishes, only: [:create, :destroy ]
    resources :guide_tags, only: [:create, :destroy ]
    get 'path', to: 'guides#path', as: 'path'
  end
  resources :reviews, only: [:destroy]

  resources :conversations do
    resources :messages
  end
  mount ActionCable.server => "/cable"
end

app/views/shared/_category_cards.html.erb
<div class="category-cards-wrapper">
  <div class="category-cards-container mt-3">
    <div class="category" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1476362174823-3a23f4aa6d76?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80);">
      <h3 class="px-3 pt-3">History</h3>
      <p class="px-3">54 guides</p>
    </div>
    <div class="category" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1511690656952-34342bb7c2f2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60);">
      <h3 class="px-3 pt-3">Food</h3>
      <p class="px-3">33 guides</p>
    </div>
    <div class="category" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1508923567004-3a6b8004f3d7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60);">
      <h3 class="px-3 pt-3">Adventure</h3>
      <p class="px-3">47 guides</p>
    </div>
    <div class="category" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1561527261-2fa922171984?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60);">
      <h3 class="px-3 pt-3">Nature</h3>
      <p class="px-3">29 guides</p>
    </div>
    <div class="category" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1485236715568-ddc5ee6ca227?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60);">
      <h3 class="px-3 pt-3">Horror</h3>
      <p class="px-3">66 guides</p>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_guide_cards.html.erb
<div class="cards-container mt-3">

  <% guides.each do |guide| %>
  <%= link_to guide_path(guide), class: 'guide-link' do%>
    <div class="card-box">

      <div class="image" style="background-image: url(<%= guide.image %>);">
        <p id="card-location"><span><i class="fas fa-map-marker-alt"></i></span>
          <%= guide.location %></p>
      </div>

      <div class="contentz p-2">
        <div class="info">
          <h3 class="card-title"><%=guide.title%></h3>
          <div class="d-flex">
            <div class="info-item d-flex align-items-center pr-1 pt-1">
              <span class="info-icon px-1"><i class="fas fa-route"></i></span>
              <p><strong><%= guide.distance %> km</strong></p>
            </div>
            <div class="info-item d-flex align-items-center px-1 pt-1">
              <span class="info-icon px-1"><i class="far fa-clock"></i></span>
              <p> <strong><%= guide.duration %> hs</strong></p>
            </div>
            <div class="info-item d-flex align-items-center px-1 pt-1">
              <% if guide.category == "history" %>
                <span class="info-icon px-1"><i class="fas fa-landmark"></i></i></span>
              <% elsif guide.category == "nature" %>
                <span class="info-icon px-1"><i class="fas fa-seedling"></i></span>
              <% elsif guide.category == "food" %>
                <span class="info-icon px-1"><i class="fas fa-utensils"></i></span>
              <% elsif guide.category == "adventure" %>
                <span class="info-icon px-1"><i class="fas fa-mountain"></i></span>
              <% elsif guide.category == "horror" %>
                <span class="info-icon px-1"><i class="fas fa-dizzy"></i></span>
              <% end %>
              <p><strong><%= guide.category %> </strong></p>
            </div>
          </div>
        </div>
        <div class="links-container">
          <% if current_user == guide.user %>
            <%= link_to 'Itinerary', guide_path_path(guide), class: 'link' %>
          <% else %>
            <div class="avatar-position mt-2">
              <%= image_tag(guide.user.avatar, class: "avatar", alt: "avatar") %>
              <p class="pl-1"><%= guide.user.full_name %></p>
            </div>
          <% end %>
        </div>
      </div>

      <% if current_user != guide.user %>
        <div class="price">
          <p><strong><%= humanized_money_with_symbol(guide.price) %></strong></p>
        </div>
      <% end %>
    </div>
  <% end %>
  <%end %>
</div>

app/views/shared/_navbar.html.erb
<% if current_user.nil? %>
  <nav class="navbar home-navbar navbar-expand-lg">
    <div class="button-holder">
      <%= link_to "Log in", new_user_session_path, class: "link link-dark"  %>
      <%= link_to "Sign up", new_user_registration_path, class: "link link-dark"  %>
    </div>
  </nav>
<% else %>
<nav class="navbar navbar-expand-lg navbar-light">
  <a class="navbar-brand" href="/dashboard"><i class="fas fa-map-marked-alt" id="logo"></i></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <%= link_to "Dashboard", dashboard_path, class: "nav-link"  %>
      </li>
      <li class="nav-item">
        <%= link_to "Explore", guides_path, class: "nav-link"  %>
      </li>
      <li class="nav-item">
        <%= link_to "Messages", conversations_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Account", edit_user_registration_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <a href="#" class="nav-link">Settings</a>
      </li>
      <li class="nav-item">
        <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>
<% end %>

app/views/shared/_reviews.html.erb
<% if @reviews.blank? %>
  <p>There are no reviews yet for this guide</p>
<% else %>
  <% @average.to_i.times do %>
    <span><i class="fas fa-star" id="star-icon"></i></span>
  <% end %>
  <% (5 - @average.to_i).times do %>
    <span><i class="far fa-star" id="star-icon"></i></span>
  <% end %>
  <span><%= @average %> (<%= @reviews.count %>)</span>
<% end %>