config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:'pages#home'

  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'

  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end

  resources :guides do
    resources :reviews, only: [:index, :new, :create]
    resources :stops, only: [:index, :new, :create] do
      resources :itineraries, only: [:new, :create]
    end
    resources :wishes, only: [:create, :destroy ]
    resources :guide_tags, only: [:create, :destroy ]
    get 'path', to: 'guides#path', as: 'path'
  end
  resources :reviews, only: [:destroy]

  resources :conversations do
    resources :messages
  end
  mount ActionCable.server => "/cable"
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :guide
  belongs_to :user
  monetize :amount_cents
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    guide = Guide.find(params[:guide_id])
    order = Order.create!(guide: guide, user: current_user, amount: guide.price, state: 'pending')
    redirect_to new_order_payment_path(order)
  end

  def show
    @order = Order.find(params[:id])
    @guide = @order.guide
  end
end

app/views/orders/show.html.erb
<div class="img-container">
  <div class="guide-image", style="background-image: url(https://images.unsplash.com/photo-1448906654166-444d494666b3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80);">
  </div>
  <div class="btn-heart">
      <%= link_to guide_wishes_path(@guide), method: :post, remote: true do %>
        <span><i class="fas fa-heart" id="heart-icon"></i></span>
      <% end %>
    </div>
</div>

<div class="show-container">

  <div class="reviews">
    <%= render 'shared/reviews' %>
  </div>

  <div class="show-title">
    <h3><%= @guide.title %></h3>
    <p id="location"><%= @guide.location %></p>
  </div>

  <div class="show-overview">
    <p><%= @guide.overview %></p>
  </div>

    <div class="sho-box-view">
      <div class="sho-box-item">
        <h5><%= @guide.distance %> KM</h5>
        <span class="sho-icon"><i class="fas fa-route"></i></span>
      </div>
      <div class="sho-box-item">
        <h5><%= @guide.duration %> HRs</h5>
        <span class="sho-icon"><i class="far fa-clock"></i></span>
      </div>
      <div class="sho-box-item">
        <h5><%= @guide.category %></h5>
        <span class="sho-icon"><i class="fas fa-mountain"></i></span>
      </div>
      <div class="sho-box-item">
        <h5><%= @guide.user.full_name %></h5>
        made this guide
      </div>
    </div>

  <% if @guide.user == current_user  %>
    <%= link_to "Edit", edit_guide_path(@guide), class: "myButton"%>
    <%= link_to "Delete", guide_path(@guide), method: :delete, class: "myButton",
        data: { confirmation: "Are you sure?"} %>
  <% else %>
    <div class="btn btn-large btn-dark">
      <%= form_tag orders_path do %>
        <%= hidden_field_tag "guide_id", @guide.id %>
        <%= submit_tag "Purchase", class: "whiter" %>
      <% end %>
    </div>
  <% end %>

</div>

<div id="reviews">
  <% if @guide.reviews.blank? %>
    <p>Be the first to leave a review for <%= @order.guide.title %></p>
  <% else %>
    <ul>
      <% @guide.reviews.each do |review| %>
        <%= render 'reviews/review', review: review %>
      <% end %>
    </ul>
  <% end %>
</div>
<div id="new-review">
  <%= link_to "Add a Review", new_guide_review_path(@guide), remote: true %>
</div>