config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:'pages#home'

  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'

  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end

  resources :guides do
    resources :reviews, only: [:index, :new, :create]
    resources :stops, only: [:index, :new, :create] do
      resources :itineraries, only: [:new, :create]
    end
    resources :wishes, only: [:create, :destroy ]
    resources :guide_tags, only: [:create, :destroy ]
    get 'path', to: 'guides#path', as: 'path'
  end
  resources :reviews, only: [:destroy]

  resources :conversations do
    resources :messages
  end
  mount ActionCable.server => "/cable"
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_order

  def new
  end

  def create
    customer = Stripe::Customer.create(
      source: params[:stripeToken],
      email:  params[:stripeEmail]
    )

    charge = Stripe::Charge.create(
      customer:     customer.id,  # You should store this customer id and re-use it.
      amount:       @order.amount_cents,
      description:  "Payment for guide #{@order.guide.title} for order #{@order.id}",
      currency:     @order.amount.currency
    )

    @order.update(payment: charge.to_json, state: 'paid')
    redirect_to order_path(@order)

    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_order_payment_path(@order)
  end

  private

  def set_order
    @order = current_user.orders.where(state: 'pending').find(params[:order_id])
  end
end

app/views/payments/new.html.erb
<div class='padding'>
  <h1>Guide Show Page</h1>

  <h3><%= @order.guide.title %></h3>

  <p>Location: <%= @order.guide.location %></p>

  <p>Overview: <%= @order.guide.overview %></p>

  <p>Distance: <%= @order.guide.distance %> km </p>

  <p>Duration <%= @order.guide.duration %> hs</p>

  <p>Category: <%= @order.guide.category %> </p>

  <p>Created by: <%= @order.guide.user.full_name %></p>

  <div id="reviews">
    <% if @order.guide.reviews.blank? %>
      <p>There are no reviews yet for <%= @order.guide.title %></p>
    <% else %>
      <ul>
        <% @order.guide.reviews.each do |review| %>
          <%= render 'reviews/review', review: review %>
        <% end %>
      </ul>
    <% end %>
  </div>

  <%= form_tag order_payments_path(@order) do %>
    <article>
      <label class="amount">
        <span>Amount: <%= humanized_money_with_symbol(@order.amount) %></span>
      </label>
    </article>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
      data-name="Email"
      data-email="<%= current_user.email %>"
      data-description="Order <%= @order.guide.title %>"
      data-amount="<%= @order.amount_cents %>"
      data-currency="<%= @order.amount.currency %>"></script>
  <% end %>

</div>